id: P005453
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1AC232
  title: 'བཅོམ་ལྡན་འདས་རྒྱལ་བ་ཤཱཀྱ་ཐུབ་པའི་རྣམ་ཐར། '
  author: ''
  volumes:
    6a1194abca4d4429b93b1db64988368a:
      image_group_id: I2PD17903
      title: ''
      volume_number: 1
      total_pages: 306
      base_file: v001.txt
